# Generated by Django 4.1.4 on 2022-12-26 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 17, 14, 58, 469994)),
        ),
    ]
