# Generated by Django 4.1.4 on 2023-01-02 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_fen_alter_game_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='currMove1',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='game',
            name='currMove2',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='game',
            name='whiteTurn',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 15, 20, 43, 64829)),
        ),
    ]
