# Generated by Django 4.1.4 on 2023-01-02 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_game_currmove1_game_currmove2_game_whiteturn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 16, 2, 56, 301414)),
        ),
        migrations.AlterField(
            model_name='game',
            name='currMove1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='currMove2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='fen',
            field=models.CharField(default='', max_length=100),
        ),
    ]
